---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-chef-dk
description: Install chef-dk through ansible
tags:
  - ansible
  - ansible-role
  - chef-dk
github:
  has_issues: true
  has_projects: false
  has_wiki: false
