---
- name: Install chefdk-{{ chef_dk.version }}
  when: ansible_distribution == 'Ubuntu'
  apt:
    deb: https://packages.chef.io/files/stable/chefdk/{{ chef_dk_version }}/{{ ansible_distribution | lower}}/{{ ansible_distribution_version }}/chefdk_{{ chef_dk_version }}-1_amd64.deb
  register: chef_dk_install

- name: Install chefdk-{{ chef_dk.version }}
  when: ansible_distribution == 'Debian'
  apt:
    deb: https://packages.chef.io/files/stable/chefdk/{{ chef_dk_version }}/{{ ansible_distribution | lower}}/{{ ansible_lsb.major_release }}/chefdk_{{ chef_dk_version }}-1_amd64.deb
  register: chef_dk_install

# - name: Install required packages
#   apt: name={{ item }} state=present
#   with_items:
#     - python-setuptools
#     - python-pip
#     - python-dev
#     - build-essential
#     - python3
#     - python3-dev
#     - python3-pip
#     - libssl-dev
#     - libffi-dev
#     - libxml2-dev
#     - libxslt1-dev
