---
- name: Include ansible_distribution and ansible_os_family tasks
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

# - include_tasks: user.yml
#   with_items: "{{ chef_dk_users }}"
#   loop_control:
#     loop_var: user_item
#   become: true
#   become_user: "{{ user_item.name }}"
